# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eCS_4SgzLYnI6JRjfR6ugTW7bN9O4lv3

# 라벨링
"""

japonica_norm = [fn for fn in os.listdir(f'{base_ds}/japonica_norm') if fn.endswith('.png')]
japonica_extra = [fn for fn in os.listdir(f'{base_ds}/japonica_extra') if fn.endswith('.png')]
indica_norm = [fn for fn in os.listdir(f'{base_ds}/indica_norm') if fn.endswith('.png')]
indica_extra = [fn for fn in os.listdir(f'{base_ds}/indica_extra') if fn.endswith('.png')]
rice = [japonica_norm, japonica_extra, indica_norm, indica_extra]
rice_classes = []
for i in os.listdir('imgs/train'):
    rice_classes+=[i]
rice_classes.sort()

"""# 시각화"""

image_count = len(list(base_ds.glob('*/*.png')))
print(f'Total images: {image_count}')
print(f'Total number of classes: {len(rice_classes)}')
count = 0
rice_count = []
for x in rice_classes:
  print(f'Total {x} images: {len(rice[count])}')
  rice_count.append(len(rice[count]))
  count += 0

sns.set_style('darkgrid')
sns.barplot(x=rice_classes, y=rice_count, palette="Blues_d")
plt.show()